"""Security metric collector.

Reads security tool output files if present:
  - bandit-report.json (generated by security workflow)
  - pip-audit-report.json (generated by security workflow)

Falls back gracefully when reports are absent.
Does NOT run security tools directly (too slow for local runs).
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class BanditMetrics:
    available: bool = False
    high_severity: int = 0
    medium_severity: int = 0
    low_severity: int = 0
    total_findings: int = 0
    status: str = "UNKNOWN"  # PASS | FAIL | UNAVAILABLE

    def to_dict(self) -> dict[str, Any]:
        return {
            "available": self.available,
            "status": self.status,
            "total_findings": self.total_findings,
            "high_severity": self.high_severity,
            "medium_severity": self.medium_severity,
            "low_severity": self.low_severity,
        }


@dataclass
class DependencyVulnMetrics:
    available: bool = False
    total_vulnerabilities: int = 0
    critical: int = 0
    high: int = 0
    medium: int = 0
    low: int = 0
    affected_packages: list[str] = field(default_factory=list)
    status: str = "UNKNOWN"

    def to_dict(self) -> dict[str, Any]:
        return {
            "available": self.available,
            "status": self.status,
            "total_vulnerabilities": self.total_vulnerabilities,
            "critical": self.critical,
            "high": self.high,
            "medium": self.medium,
            "low": self.low,
            "affected_packages": self.affected_packages[:10],
        }


@dataclass
class SecurityMetrics:
    bandit: BanditMetrics = field(default_factory=BanditMetrics)
    dependencies: DependencyVulnMetrics = field(default_factory=DependencyVulnMetrics)
    secret_scan_status: str = "UNKNOWN"
    codeql_status: str = "UNKNOWN"
    overall_status: str = "UNKNOWN"

    def to_dict(self) -> dict[str, Any]:
        return {
            "overall_status": self.overall_status,
            "bandit": self.bandit.to_dict(),
            "dependencies": self.dependencies.to_dict(),
            "secret_scan": self.secret_scan_status,
            "codeql": self.codeql_status,
        }


def _load_bandit_report(report_path: Path) -> BanditMetrics:
    """Parse bandit JSON report."""
    m = BanditMetrics(available=True)
    try:
        data: dict[str, Any] = json.loads(report_path.read_text(encoding="utf-8"))
        results: list[dict[str, Any]] = data.get("results", [])
        m.total_findings = len(results)
        for r in results:
            sev = (r.get("issue_severity") or "").upper()
            if sev == "HIGH":
                m.high_severity += 1
            elif sev == "MEDIUM":
                m.medium_severity += 1
            elif sev == "LOW":
                m.low_severity += 1
        m.status = "FAIL" if m.high_severity > 0 else "PASS"
    except (OSError, json.JSONDecodeError, KeyError):
        m.available = False
        m.status = "UNAVAILABLE"
    return m


def _load_pip_audit_report(report_path: Path) -> DependencyVulnMetrics:
    """Parse pip-audit JSON report."""
    m = DependencyVulnMetrics(available=True)
    try:
        data: list[dict[str, Any]] | dict[str, Any] = json.loads(
            report_path.read_text(encoding="utf-8")
        )
        # pip-audit v2 format: list of {name, version, vulns: [...]}
        packages: list[dict[str, Any]] = data if isinstance(data, list) else []
        if isinstance(data, dict):
            packages = data.get("dependencies", [])
        for pkg in packages:
            vulns: list[dict[str, Any]] = pkg.get("vulns", [])
            if vulns:
                m.affected_packages.append(pkg.get("name", "?"))
                for _v in vulns:
                    m.total_vulnerabilities += 1
                    # pip-audit doesn't always include severity; default to high
                    m.high += 1
        m.status = "FAIL" if m.total_vulnerabilities > 0 else "PASS"
    except (OSError, json.JSONDecodeError, TypeError):
        m.available = False
        m.status = "UNAVAILABLE"
    return m


def collect_security(root: Path) -> SecurityMetrics:
    """Collect security metrics from available report files."""
    m = SecurityMetrics()

    # Look for reports in common locations
    bandit_candidates = [
        root / "bandit-report.json",
        root / "reports" / "bandit-report.json",
    ]
    for p in bandit_candidates:
        if p.exists():
            m.bandit = _load_bandit_report(p)
            break
    else:
        m.bandit.status = "UNAVAILABLE"

    audit_candidates = [
        root / "pip-audit-report.json",
        root / "dep-audit.json",
        root / "reports" / "pip-audit-report.json",
    ]
    for p in audit_candidates:
        if p.exists():
            m.dependencies = _load_pip_audit_report(p)
            break
    else:
        m.dependencies.status = "UNAVAILABLE"

    # Secret scan: inferred from pre-commit config presence
    precommit = root / ".pre-commit-config.yaml"
    if precommit.exists():
        text = precommit.read_text(encoding="utf-8", errors="replace")
        m.secret_scan_status = "CONFIGURED" if "detect-private-key" in text else "PARTIAL"
    else:
        m.secret_scan_status = "NOT_CONFIGURED"

    # CodeQL: inferred from workflow presence
    codeql_workflow = root / ".github" / "workflows" / "security.yml"
    codeql_config = root / ".github" / "codeql" / "codeql-config.yml"
    if codeql_workflow.exists() and codeql_config.exists():
        m.codeql_status = "CONFIGURED"
    else:
        m.codeql_status = "NOT_CONFIGURED"

    # Overall status
    if m.bandit.status == "FAIL" or m.dependencies.status == "FAIL":
        m.overall_status = "FAIL"
    elif m.bandit.status == "PASS" or m.dependencies.status == "PASS":
        m.overall_status = "PASS"
    else:
        m.overall_status = "UNKNOWN"

    return m
